export const USER_ACTIONS = {
  SIGN_UP_START: "SIGN_UP_START",
  SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",

  LOGIN_START: "LOGIN_START",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",

  LOGOUT_START: "LOGOUT_SUCCESS",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",

  EDIT_INFO_START: "EDIT_INFO_START",
  EDIT_INFO_SUCCESS: "EDIT_INFO_SUCCESS",
};

export const TEST_ACTIONS = {
  TEST: "TEST",
};

const TYPES = {
  USER_ACTIONS,
  TEST_ACTIONS,
};

export default TYPES;
